FROM alpine:latest

# Tor ve bridge desteği kurulumu
RUN apk add --no-cache tor obfs4proxy && \
    rm -rf /var/cache/apk/*

# Entrypoint script
COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/

EXPOSE 9150
EXPOSE 5353/udp

HEALTHCHECK --interval=60s --timeout=15s --start-period=30s --retries=3 \
  CMD nc -z 127.0.0.1 9150 || exit 1

USER tor
ENTRYPOINT ["docker-entrypoint.sh"]
