name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Debian (default) image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: |
            mstfknn/tor-proxy:latest
            mstfknn/tor-proxy:debian
          build-args: |
            APT_UPDATED=1

      - name: Build and push Alpine image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          pull: true
          platforms: linux/amd64,linux/arm64
          tags: mstfknn/tor-proxy:alpine